# Generated by Django 5.0.6 on 2024-05-27 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="beer",
            name="Id_of_feedback",
        ),
        migrations.RemoveField(
            model_name="shop",
            name="Discounts",
        ),
        migrations.RemoveField(
            model_name="shop",
            name="id",
        ),
        migrations.AddField(
            model_name="beer",
            name="Feedback_id",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="main.feedback",
            ),
        ),
        migrations.AddField(
            model_name="shop",
            name="Shop_id",
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="users",
            name="Bonuses",
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name="Discounts",
            fields=[
                (
                    "Shop_id",
                    models.IntegerField(default=1, primary_key=True, serialize=False),
                ),
                ("Amount", models.IntegerField(default=0)),
                (
                    "Discount",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.beer",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="shop",
            name="Discounts_id",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="main.discounts",
            ),
        ),
        migrations.CreateModel(
            name="Goods",
            fields=[
                (
                    "Shop_id",
                    models.IntegerField(default=1, primary_key=True, serialize=False),
                ),
                (
                    "Beer_id",
                    models.ForeignKey(
                        default=0,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.beer",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="shop",
            name="Beer_id",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="main.goods"
            ),
        ),
    ]
