# Generated by Django 5.0.6 on 2024-05-30 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="discounts",
            name="Beer_id",
            field=models.IntegerField(default=0),
        ),
    ]
