# Generated by Django 5.0.6 on 2024-06-01 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_discounts_beer_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shop",
            name="Job",
            field=models.IntegerField(default=0),
        ),
    ]
