# Generated by Django 5.0.6 on 2024-05-28 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_remove_beer_id_of_feedback_remove_shop_discounts_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedback",
            name="Beer_id",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="beer",
            name="Name",
            field=models.CharField(default="Балтика", max_length=128),
        ),
        migrations.AlterField(
            model_name="beer",
            name="Origin",
            field=models.CharField(default="Россия", max_length=128),
        ),
    ]
