# Generated by Django 5.0.6 on 2024-05-28 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_feedback_beer_id_alter_beer_name_alter_beer_origin"),
    ]

    operations = [
        migrations.AddField(
            model_name="beer",
            name="Amount",
            field=models.IntegerField(default=500),
        ),
    ]
