# Generated by Django 5.0.6 on 2024-06-10 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_alter_shop_job"),
    ]

    operations = [
        migrations.RenameField(
            model_name="shop",
            old_name="Shop_id",
            new_name="id",
        ),
    ]
