# Generated by Django 5.0.6 on 2024-05-28 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_beer_strength"),
    ]

    operations = [
        migrations.AddField(
            model_name="shop",
            name="Address",
            field=models.CharField(default="Бульвар", max_length=256),
        ),
    ]
