# Generated by Django 5.0.6 on 2024-05-29 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_shop_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="beer",
            name="Image",
            field=models.ImageField(null=True, upload_to="beers/"),
        ),
    ]
