# Generated by Django 5.0.6 on 2024-05-29 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_beer_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="beer",
            name="Feedback_id",
        ),
        migrations.AlterField(
            model_name="beer",
            name="Image",
            field=models.ImageField(null=True, upload_to="beers"),
        ),
    ]
