# Generated by Django 5.0.6 on 2024-05-29 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0008_remove_beer_feedback_id_alter_beer_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="beer",
            name="Image",
            field=models.CharField(default="images/beers/baltika_7.jpg", max_length=128),
        ),
    ]
