# Generated by Django 5.0.6 on 2024-05-30 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0009_alter_beer_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedback",
            name="User_id",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="beer",
            name="Amount",
            field=models.FloatField(default=500),
        ),
    ]
