# Generated by Django 5.0.6 on 2024-05-30 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0010_feedback_user_id_alter_beer_amount"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="feedback",
            name="User_id",
        ),
        migrations.AddField(
            model_name="feedback",
            name="Username",
            field=models.CharField(default=0, max_length=128),
        ),
    ]
