# Generated by Django 5.0.6 on 2024-06-13 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Beer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.CharField(default="Балтика", max_length=128)),
                (
                    "Image",
                    models.CharField(
                        default="images/beers/baltika_7.jpg", max_length=128
                    ),
                ),
                ("Amount", models.FloatField(default=500)),
                ("Strength", models.FloatField(default=9.9)),
                ("Origin", models.CharField(default="Россия", max_length=128)),
                ("Price", models.IntegerField(default=100)),
                ("Description", models.CharField(default="", max_length=512)),
                ("Mark", models.IntegerField(default=5)),
            ],
            options={
                "db_table": "Beers",
            },
        ),
        migrations.CreateModel(
            name="Discounts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Shop_id", models.IntegerField(default=0)),
                ("Amount", models.IntegerField(default=0)),
                ("Beer_id", models.IntegerField(default=0)),
            ],
            options={
                "db_table": "Discounts",
            },
        ),
        migrations.CreateModel(
            name="Goods",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Shop_id", models.IntegerField(default=0)),
                ("Beer_id", models.IntegerField(default=0)),
            ],
            options={
                "db_table": "Goods",
            },
        ),
        migrations.CreateModel(
            name="Shop",
            fields=[
                (
                    "id",
                    models.IntegerField(default=1, primary_key=True, serialize=False),
                ),
                ("Job", models.IntegerField(default=0)),
                ("Address", models.CharField(default="Бульвар", max_length=256)),
            ],
            options={
                "db_table": "Shops",
            },
        ),
    ]
